import type { BranchIF } from "./types/types.branch";
import type { OffshootIF } from "./types";
import type { ForestIF } from "./types/types.forest";
import type { TreeIF, TreeName, TreeParams, TreeValuation } from "./types/types.trees";
import type { ChangeIF, Info, InfoParams, SubscribeFn } from "./types/types.shared";
import type { PartialObserver } from "rxjs";
export declare const CLONE_NAME = "!CLONE!";
export default class Tree<ValueType> implements TreeIF<ValueType> {
    forest: ForestIF;
    readonly name: TreeName;
    private params?;
    constructor(forest: ForestIF, name: TreeName, params?: TreeParams<ValueType>);
    get isUncacheable(): boolean;
    private stream;
    next(next: ValueType, name?: string): void;
    rollback(time: number, message: string): void;
    offshoots?: OffshootIF<ValueType>[];
    root?: BranchIF<ValueType>;
    top?: BranchIF<ValueType>;
    grow(change: ChangeIF<ValueType>): BranchIF<ValueType>;
    validate(value: ValueType): TreeValuation<ValueType>;
    _maybeCache(): void;
    get subject(): import("rxjs").Observable<ValueType>;
    subscribe(observer: PartialObserver<ValueType> | SubscribeFn<ValueType>): import("rxjs").Subscription;
    valueAt(at: number): ValueType | undefined;
    get value(): ValueType;
    private _notes?;
    addNote(message: string, params?: InfoParams): void;
    hasNoteAt(time: number): boolean;
    notes(fromTime: number, toTime?: number): Info[];
}
