import {
  IMAGE_OS,
  LOGO_SIZE,
  SUMMARY_LM,
  TEXT_SIZE_EXTRA,
  MIN_HEADER_SIZE,
  scale,
  scaleRem,
  u,
  LOGO_MARGIN_SIZE,
} from './themeConstants';

export const layerStyles = {
  nextButton: {
    position: 'fixed',
    right: '25px',
    top: 'calc((100% - var(--nav-button-height))/2)',
    height: `var(--nav-button-height)`,
    width: `var(--nav-button-width)`,
  },
  prevButton: {
    position: 'fixed',
    left: '25px',
    top: 'calc((100% - var(--nav-button-height))/2)',
    height: `var(--nav-button-height)`,
    width: `var(--nav-button-width)`,
  },
  logo: {
    position: 'fixed',
    left: `calc(10px - ${u(LOGO_MARGIN_SIZE)})`,
    top: `calc(10px - ${u(LOGO_MARGIN_SIZE)})`,
    width: `calc(${u(LOGO_SIZE)} + (2 * ${u(LOGO_MARGIN_SIZE)}))`,
    minHeight: `calc(${u(LOGO_SIZE)} + (2 * ${u(LOGO_MARGIN_SIZE)}))`,
    zIndex: 100,
    overflow: 'show',
    backgroundColor: 'logoCircle',
    borderRadius: '50%',
    textAlign: 'center',
    paddingX: u(LOGO_MARGIN_SIZE),
    paddingTop: u(LOGO_MARGIN_SIZE),
  },
  root: {
    backgroundColor: 'transparent',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'stretch',
    alignContent: 'stretch',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  rootContent: {
    position: 'relative',
    height: '100%',
    width: '100%',
    overflow: 'auto',
  },
  content: {
    paddingX: { base: '10px', md: '1rem', lg: '1.5rem', xl: '2rem' },
    paddingY: scale(7, false),
    bgGradient: `linear(var(--chakra-colors-contentTransparent) 0px, 
      var(--chakra-colors-content) 100px, 
      var(--chakra-colors-content) calc(100% - 150px), 
      var(--chakra-colors-contentTransparent) 100%)`.replace(/\n/g, ' '),
    color: 'contentText',
    display: 'block',
  },
  pageTitleSummary: {
    fontSize: TEXT_SIZE_EXTRA,
    lineHeight: '160%',
    marginLeft: SUMMARY_LM,
    marginTop: 3,
    maxWidth: '600px',
  },
  pageImage: {
    position: 'absolute',
    left: IMAGE_OS,
    top: IMAGE_OS,
    zIndex: 5,
    borderRadius: '50%',
    overflow: 'hidden',
  },
  pageColumnHeader: {
    marginLeft: SUMMARY_LM,
    minHeight: MIN_HEADER_SIZE,
    marginBottom: 4,
    zIndex: 10,
  },
  pageColumnBody: {
    position: 'relative',
  },
  pageColumnContainer: {
    width: '100%',
    minHeight: '100vw',
    maxWidth: '100vw',
    display: 'flex',
    flexDirection: 'row',
    flexBasis: 0,
    alignContent: 'stretch',
    justifyContent: 'center',
  },
  pageColumn: {
    position: 'relative',
    maxWidth: 'calc(min(100vw, 1024px))',
    flexDirection: 'column',
    flex: 1,
    flexBasis: 0,
    paddingX: { base: '25px', md: '2rem', lg: '3rem', xl: '5rem' },
    display: 'flex',
    bgGradient: `linear(
    90deg, 
    var(--chakra-colors-pageColumnTransparent) 0px,
    var(--chakra-colors-pageColumn) 20px,
    var(--chakra-colors-pageColumn) calc(100% - 20px),
    var(--chakra-colors-pageColumnTransparent)  100%)`.replace(/\n/g, ''),
  },
  conceptsImage: {
    width: '100%',
    height: '100%',
    position: 'fixed',
    backgroundImage: 'url("/img/forest-enhance.png")',
    backgroundPosition: 'left top',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
  },
  mdCode: {
    px: 8,
    py: 3,
    marginY: 2,
    overflowY: 'auto',
    fontSize: scaleRem(0.7),
    lineHeight: '110%',
  },
};
