import { textStyles } from './textStyles';
import {
  IMAGE_OS,
  LOGO_SIZE,
  SUMMARY_LM,
  scaleRem,
  u,
  LOGO_MARGIN_SIZE,
  IMAGE_TOP_OS,
  scale,
} from './themeConstants';

const BUTTON_X = { base: '15px', md: '30px', lg: '50px' };
const CALLOUT_PADDING_Y = { base: 3, md: 3.5, xl: 4 };
const CALLOUT_PADDING_X = { base: 4, sm: 4, md: 5, xl: 6 };
const SEE_MORE_BORDER = '1px solid var(--chakra-colors-blackAlpha-100)';
const HIGHLIGHT_SHADOW =
  'rgba(0, 0, 0, 0.15) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px;';
export const layerStyles = {
  apiMenuSection: {
    paddingX: { base: 3, sm: 4, md: 5, lg: 8 },
    marginY: { base: 5, sm: 7, md: 9, lg: 12 },
  },
  conceptsHeader: {
    marginLeft: { base: '50px', sm: '80px', md: '100px' },
    marginBottom: 2,
    zIndex: 10,
  },
  conceptsImage: {
    width: '100%',
    height: '100%',
    position: 'fixed',
    backgroundImage: 'url("/img/forest-enhance.png")',
    backgroundPosition: 'left top',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
  },
  conceptsSummary: {
    ...textStyles.conceptsSummary,
    marginLeft: SUMMARY_LM,
    marginTop: 3,
    maxWidth: '600px',
  },
  content: {
    paddingX: { base: '10px', md: '1rem', lg: '1.5rem', xl: '2rem' },
    paddingY: '30px',
    color: 'contentText',
    display: 'block',
  },
  highlight: {
    paddingX: CALLOUT_PADDING_X,
    paddingY: CALLOUT_PADDING_Y,
    borderRadius: { base: '0', md: 'md' },
    backgroundColor: 'menuContainer',
    userSelect: 'none',
    cursor: 'pointer',
    boxShadow: { base: '', md: HIGHLIGHT_SHADOW },
  },
  highlightContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'stretch',
    width: '100%',
    marginY: { base: '0.5rem', sm: '1rem' },
    paddingX: { base: '2px', sm: '1rem', md: '2rem', lg: '5rem' },
  },
  highlightText: {
    marginTop: '0.5rem',
  },
  highlights: {
    display: 'flex',
    maxWidth: u(1024),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    alignContent: 'stretch',
    width: '100%',
    gap: '5px',
    flexWrap: { base: 'nowrap', sm: 'wrap' },
    flex: 1,
  },
  highlightsColumn: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    alignItems: 'stretch',
    paddingX: { base: 2, sm: 2, md: 5 },
  },
  homeHeader: {},
  list: {
    paddingLeft: 8,
    marginBottom: '1em',
  },
  logo: {
    position: 'fixed',
    right: `calc(10px - ${u(LOGO_MARGIN_SIZE)})`,
    top: `calc(10px - ${u(LOGO_MARGIN_SIZE)})`,
    width: `calc(${u(LOGO_SIZE)} + (2 * ${u(LOGO_MARGIN_SIZE)}))`,
    minHeight: `calc(${u(LOGO_SIZE)} + (2 * ${u(LOGO_MARGIN_SIZE)}))`,
    zIndex: 100,
    overflow: 'show',
    backgroundColor: 'logoCircle',
    borderRadius: '50%',
    textAlign: 'center',
    paddingX: u(LOGO_MARGIN_SIZE),
    paddingTop: u(LOGO_MARGIN_SIZE),
  },
  mdCode: {
    px: 8,
    py: 3,
    marginY: 2,
    overflowY: 'auto',
    fontSize: scaleRem(0.7),
    lineHeight: '110%',
  },
  menuSection: {
    paddingX: CALLOUT_PADDING_X,
    paddingY: CALLOUT_PADDING_Y,
    transition: 'background-color',
    transitionDuration: '1s',
    borderRadius: { base: 'sm', md: 'md' },
    userSelect: 'none',
    cursor: 'pointer',
    backgroundColor: 'menuContainer',
    boxShadow: { base: '', md: HIGHLIGHT_SHADOW },
    _hover: {
      backgroundColor: 'highlightContainerHover',
    },
  },
  nextButton: {
    position: 'fixed',
    right: BUTTON_X,
    cursor: 'pointer',
    top: {
      base: 'calc((100% - var(--nav-button-height-sm))/2)',
      md: 'calc((100% - var(--nav-button-height))/2)',
    },
    height: {
      base: `var(--nav-button-height-sm)`,
      md: `var(--nav-button-height)`,
    },
    width: {
      base: `var(--nav-button-width-sm)`,
      md: `var(--nav-button-width)`,
    },
  },
  pageColumn: {
    position: 'relative',
    maxWidth: 'calc(min(100vw, 1024px))',
    flexDirection: 'column',
    flex: 1,
    flexBasis: 0,
    paddingX: { base: 0, md: '2rem', lg: '3rem', xl: '5rem' },
    display: 'flex',
    /* bgGradient: `linear(
    90deg,
    var(--chakra-colors-pageColumnTransparent) 0px,
    var(--chakra-colors-pageColumn) 20px,
    var(--chakra-colors-pageColumn) calc(100% - 20px),
    var(--chakra-colors-pageColumnTransparent)  100%)`.replace(/\n/g, ''), */
  },
  pageColumnBody: {
    position: 'relative',
    flex: 1,
    backgroundColor: 'contentBackground',
    boxShadow: `0 0 30px 40px var(--chakra-colors-contentBackground)`.replace(/\n/g, ''),
  },
  pageColumnContainer: {
    width: '100%',
    maxWidth: '100vw',
    display: 'flex',
    flexDirection: 'row',
    flexBasis: 0,
    flex: 1,
    alignContent: 'stretch',
    justifyContent: 'center',
    bgGradient: `linear(var(--home-header-bg1) 0%,
    var(--home-header-bg2) 20px,
    var(--home-header-bg3) 50px,
     var(--home-header-bg4) 100px)`.replace(/\n/g, ''),
  },
  pageHeader: {
    marginX: { base: 2, sm: 0 },
    marginBottom: 2,
    zIndex: 10,
  },
  pageImage: {
    position: 'absolute',
    top: IMAGE_TOP_OS,
    display: { base: 'none', sm: 'none', md: 'block' },
    left: IMAGE_OS,
    zIndex: 5,
    borderRadius: '50%',
    overflow: 'hidden',
  },
  prevButton: {
    cursor: 'pointer',
    position: 'fixed',
    zIndex: 20,
    left: BUTTON_X,
    top: {
      base: 'calc((100% - var(--nav-button-height-sm))/2)',
      md: 'calc((100% - var(--nav-button-height))/2)',
    },
    height: {
      base: `var(--nav-button-height-sm)`,
      md: `var(--nav-button-height)`,
    },
    width: { base: `var(--nav-button-width-sm)`, md: `var(--nav-button-width)` },
  },
  root: {
    backgroundColor: 'transparent',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'stretch',
    alignContent: 'stretch',
    alignItems: 'stretch',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  rootContent: {
    position: 'relative',
    height: '100%',
    width: '100%',
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'stretch',
    alignContent: 'stretch',
    alignItems: 'stretch',
  },
  sectionIcon: {
    display: 'flex',
    flexDirection: 'row',
    paddingRight: '80px',
    paddingLeft: 0,
    height: '60px',
    borderRadius: '30px',
    cursor: 'pointer',
    userSelect: 'none',
    justifyContent: 'stretch',
    '& div img': {
      opacity: 0.6,
    },
    bgColor: 'menuContainer',
    _hover: {
      backgroundColor: 'highlightContainerHover',

      '& div img': {
        opacity: 1,
      },
    },
    alignItems: 'center',
    gap: 4,
    boxShadow: { base: '', md: HIGHLIGHT_SHADOW },
  },
  sectionIconImage: {
    width: '50px',
    height: '50px',
    borderRadius: '25px',
    overflow: 'hidden',
    border: '1px solid white',
    flexGrow: 0,
    flexShrink: 0,
    flexBase: '50px',
    m: '5px',
  },
  sectionIcons: {
    marginX: { ...scale(4, 'rem'), base: '10px' },
    marginTop: scale(2, 'rem'),
  },
  sectionIconsColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  seeMoreNavbar: {
    bgGradient: 'linear(to-b, gray.300, gray.100 8px, white 30px)',
    display: 'flex',
    flexDirection: 'row',
    paddingX: 6,
    paddingY: 3,
    gap: 3,
    borderTopLeftRadius: 'lg',
    borderTopRightRadius: 'lg',
    justifyContent: 'space-between',
    borderLeft: SEE_MORE_BORDER,
    borderRight: SEE_MORE_BORDER,
    borderTop: SEE_MORE_BORDER,
  },
  seeMoreNavbarOpen: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  seeMoreNavbarFooter: {
    display: 'flex',
    flexDirection: 'row',
    paddingX: 6,
    paddingY: 3,
    marginBottom: 2,
    borderBottomLeftRadius: 'lg',
    borderBottomRightRadius: 'lg',
    justifyContent: 'space-between',
    borderLeft: SEE_MORE_BORDER,
    borderRight: SEE_MORE_BORDER,
    borderBottom: SEE_MORE_BORDER,
    backgroundColor: 'white',
  },
  seeMoreOverlay: {
    p: 3,
    px: 8,
    borderLeft: SEE_MORE_BORDER,
    borderRight: SEE_MORE_BORDER,
    backgroundColor: 'white',
  },
};
